name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore Doc_Helper.sln
      
    - name: Build
      run: dotnet build Doc_Helper.sln --configuration Debug --no-restore
      
    - name: Build Release
      run: dotnet build Doc_Helper.sln --configuration Release --no-restore