name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore Doc_Helper.sln

      - name: Install Inno Setup
        run: |
          # Download and install Inno Setup
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "innosetup.exe"
          Start-Process -FilePath "innosetup.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART" -Wait
        shell: powershell

      - name: Publish Application
        run: dotnet publish DocHelper/DocHelper.csproj --configuration Release --output ./publish --self-contained true --runtime win-x64

      - name: Build Installer
        run: |
          # Build the installer using Inno Setup
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer\DocHelper.iss"
        shell: powershell

      - name: Create Portable Version
        run: |
          # Create portable zip version
          Compress-Archive -Path ./publish/* -DestinationPath DocHelper-Portable.zip
        shell: powershell

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            DocHelper-Setup.exe
            DocHelper-Portable.zip
          body: |
            ## Doc Helper Release ${{ github.ref_name }}

            ### Features
            - Document processing with hyperlink extraction
            - Support for Word documents (.docx) and text files (.txt)
            - Automatic Document_ID and Content_ID parsing
            - Settings management for API configuration
            - Full MVVM architecture with Prism framework

            ### Changes in this release
            - Fixed NuGet restoration issues with PackageSourceMapping
            - Updated to .NET 9.0-windows for improved WPF compatibility
            - Added local NuGet.config for reliable package restoration

            ### Download Options
            - **DocHelper-Setup.exe**: Windows Installer - installs to %AppData%, creates shortcuts, handles updates
            - **DocHelper-Portable.zip**: Portable version - extract folder and run anywhere
            
            ### Quick Start
            - **Recommended**: Download `DocHelper-Setup.exe` and run installer (no admin rights required)
            - **Alternative**: Download `DocHelper-Portable.zip`, extract folder, run `DocHelper.exe`
            
            ### Features
            - Automatic installation to %AppData% folder
            - Taskbar pinning on first run
            - Logs folder creation and management
            - Self-contained - no additional .NET runtime needed

            ### Requirements
            - Windows 10/11 x64
            - No additional software required
          draft: false
          prerelease: false
