name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore Doc_Helper.sln

      - name: Install WiX Toolset
        run: |
          # Install WiX Toolset v3 (compatible with most environments)
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe" -OutFile "wix311.exe"
          Start-Process -FilePath "wix311.exe" -ArgumentList "/quiet" -Wait
        shell: powershell

      - name: Publish Application
        run: dotnet publish DocHelper/DocHelper.csproj --configuration Release --output ./publish --self-contained true --runtime win-x64

      - name: Build MSI Installer
        run: |
          # Add WiX to PATH
          $env:PATH += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
          
          # Harvest application files
          heat.exe dir "publish" -cg ApplicationFiles -gg -scom -sreg -sfrag -srd -dr APPLICATIONFOLDER -out "installer\HarvestedFiles.wxs"
          
          # Compile WiX source files
          candle.exe "installer\DocHelper-Simple.wxs" "installer\HarvestedFiles.wxs" -out "installer\"
          
          # Link to create MSI
          light.exe "installer\DocHelper-Simple.wixobj" "installer\HarvestedFiles.wixobj" -ext WixUIExtension -out "DocHelper-Setup.msi"
        shell: powershell

      - name: Create Portable Version
        run: |
          # Create portable zip version
          Compress-Archive -Path ./publish/* -DestinationPath DocHelper-Portable.zip
        shell: powershell

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            DocHelper-Setup.msi
            DocHelper-Portable.zip
          body: |
            ## Doc Helper Release ${{ github.ref_name }}

            ### Features
            - Document processing with hyperlink extraction
            - Support for Word documents (.docx) and text files (.txt)
            - Automatic Document_ID and Content_ID parsing
            - Settings management for API configuration
            - Full MVVM architecture with Prism framework

            ### Changes in this release
            - Fixed NuGet restoration issues with PackageSourceMapping
            - Updated to .NET 9.0-windows for improved WPF compatibility
            - Added local NuGet.config for reliable package restoration

            ### Download Options
            - **DocHelper-Setup.msi**: Windows MSI Installer - installs to %AppData%, handles auto-updates
            - **DocHelper-Portable.zip**: Portable version - extract folder and run anywhere
            
            ### Quick Start
            - **Recommended**: Download `DocHelper-Setup.msi` and run installer (no admin rights required)
            - **Alternative**: Download `DocHelper-Portable.zip`, extract folder, run `DocHelper.exe`
            
            ### Features
            - Automatic installation to %AppData% folder
            - Taskbar pinning on first run
            - Logs folder creation and management
            - Self-contained - no additional .NET runtime needed

            ### Requirements
            - Windows 10/11 x64
            - No additional software required
          draft: false
          prerelease: false
