name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore Doc_Helper.sln

      - name: Publish
        run: dotnet publish DocHelper/DocHelper.csproj --configuration Release --output ./publish --self-contained true --runtime win-x64

      - name: Create Release Archive
        run: |
          Compress-Archive -Path ./publish/* -DestinationPath DocHelper-Release.zip
        shell: powershell

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: DocHelper-Release.zip
          body: |
            ## Doc Helper Release ${{ github.ref_name }}

            ### Features
            - Document processing with hyperlink extraction
            - Support for Word documents (.docx) and text files (.txt)
            - Automatic Document_ID and Content_ID parsing
            - Settings management for API configuration
            - Full MVVM architecture with Prism framework

            ### Changes in this release
            - Fixed NuGet restoration issues with PackageSourceMapping
            - Updated to .NET 9.0-windows for improved WPF compatibility
            - Added local NuGet.config for reliable package restoration

            ### Installation
            1. Download DocHelper-Release.zip
            2. Extract to desired location
            3. Run DocHelper.exe

            ### Requirements
            - Windows 10/11
            - .NET 9 Runtime (included in self-contained release)
          draft: false
          prerelease: false
