name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore Doc_Helper.sln

      - name: Publish
        run: dotnet publish DocHelper/DocHelper.csproj --configuration Release --output ./publish --self-contained true --runtime win-x64

      - name: Create Release Files
        run: |
          # Create ZIP archive with all files
          Compress-Archive -Path ./publish/* -DestinationPath DocHelper-Release.zip
          
          # Create a portable version - single folder with all dependencies
          New-Item -ItemType Directory -Path "./portable" -Force
          Copy-Item -Path "./publish/*" -Destination "./portable/" -Recurse -Force
          Compress-Archive -Path ./portable/* -DestinationPath DocHelper-Portable.zip
        shell: powershell

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            DocHelper-Release.zip
            DocHelper-Portable.zip
          body: |
            ## Doc Helper Release ${{ github.ref_name }}

            ### Features
            - Document processing with hyperlink extraction
            - Support for Word documents (.docx) and text files (.txt)
            - Automatic Document_ID and Content_ID parsing
            - Settings management for API configuration
            - Full MVVM architecture with Prism framework

            ### Changes in this release
            - Fixed NuGet restoration issues with PackageSourceMapping
            - Updated to .NET 9.0-windows for improved WPF compatibility
            - Added local NuGet.config for reliable package restoration

            ### Download Options
            - **DocHelper-Release.zip**: Complete installation package with all files
            - **DocHelper-Portable.zip**: Portable version - extract and run anywhere
            
            ### Installation
            1. Download either zip file above
            2. Extract to desired location
            3. Run DocHelper.exe
            
            ### Features
            - Automatic installation to %AppData% folder
            - Taskbar pinning on first run
            - Logs folder creation and management
            - Self-contained - no additional .NET runtime needed

            ### Requirements
            - Windows 10/11 x64
            - No additional software required
          draft: false
          prerelease: false
