name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore Doc_Helper.sln

      - name: Publish Single File
        run: dotnet publish DocHelper/DocHelper.csproj --configuration Release --output ./publish-single --self-contained true --runtime win-x64 --verbosity normal

      - name: Publish Multi-File (Portable)
        run: dotnet publish DocHelper/DocHelper.csproj --configuration Release --output ./publish-multi --self-contained true --runtime win-x64 -p:PublishSingleFile=false --verbosity normal

      - name: Create Release Files
        run: |
          # Single file executable (standalone)
          Copy-Item ./publish-single/DocHelper.exe DocHelper-Standalone.exe
          
          # Multi-file version (portable folder)
          New-Item -ItemType Directory -Path "./portable" -Force
          Copy-Item -Path "./publish-multi/*" -Destination "./portable/" -Recurse -Force
          Compress-Archive -Path ./portable/* -DestinationPath DocHelper-Portable.zip
          
          # Complete release package
          Compress-Archive -Path ./publish-multi/* -DestinationPath DocHelper-Release.zip
        shell: powershell

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            DocHelper-Standalone.exe
            DocHelper-Portable.zip
            DocHelper-Release.zip
          body: |
            ## Doc Helper Release ${{ github.ref_name }}

            ### Features
            - Document processing with hyperlink extraction
            - Support for Word documents (.docx) and text files (.txt)
            - Automatic Document_ID and Content_ID parsing
            - Settings management for API configuration
            - Full MVVM architecture with Prism framework

            ### Changes in this release
            - Fixed NuGet restoration issues with PackageSourceMapping
            - Updated to .NET 9.0-windows for improved WPF compatibility
            - Added local NuGet.config for reliable package restoration

            ### Download Options
            - **DocHelper-Standalone.exe**: Single executable file - download and run immediately! 
            - **DocHelper-Portable.zip**: Portable folder version - extract and run anywhere
            - **DocHelper-Release.zip**: Complete installation package with all files
            
            ### Quick Start
            - **Easiest**: Download `DocHelper-Standalone.exe` and double-click to run
            - **Portable**: Download `DocHelper-Portable.zip`, extract folder, run `DocHelper.exe`
            
            ### Features
            - Automatic installation to %AppData% folder
            - Taskbar pinning on first run
            - Logs folder creation and management
            - Self-contained - no additional .NET runtime needed

            ### Requirements
            - Windows 10/11 x64
            - No additional software required
          draft: false
          prerelease: false
